# Generated by Django 3.2.5 on 2022-05-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=32, null=True, verbose_name='사용자명')),
                ('useremail', models.EmailField(default='', max_length=128, verbose_name='emailID')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'django_user',
            },
        ),
    ]
